services:
  grafana:
    image: grafana/grafana-enterprise:11.4.0
    user: "1000:1000"
    restart: always
    volumes:
      - "./volumes/grafana_data:/var/lib/grafana:rw"
    environment:
      - "GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL:?}"
      - "GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS:-}"
    logging:
      driver: fluentd
      options:
        tag: docker.grafana_aoirint_com.grafana.{{.ID}}
        fluentd-async: "true"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - grafana
    ports:
      - "${NGINX_HOST_PORT:?}:80/tcp"
    volumes:
      - ./nginx_templates:/etc/nginx/templates
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx
    logging:
      driver: fluentd
      options:
        tag: docker.grafana_aoirint_com.nginx.{{.ID}}
        fluentd-async: "true"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN:?}
    logging:
      driver: fluentd
      options:
        tag: docker.grafana_aoirint_com.cloudflared.{{.ID}}
        fluentd-async: "true"
